config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'home' => 'static_pages#home'
  get 'not_found' => 'static_pages#not_found'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'contacts#new'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'cities/autocomplete_city_name'
  get 'add_zone' => 'areas#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users
  resources :cities, only: [:show, :index]
  resources :areas, only: [:show, :create, :destroy, :update]
  resources :comments, only: [:create, :destroy]
  resources :contacts, only: [:create, :new]

end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :users
  has_many :areas
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  autocomplete :city, :name

  def show
    @city = City.find_by id: params[:id]
    return redirect_to not_found_path if @city.nil?
    @colors = AreaColor.all
    @areas = @city.areas.all

    @card = unique_visits "city-#{@city.id}"
    cache_location if logged_in?
  end

  def index
    if params[:search]
      @cities = City.paginate_by_sql("Select * from cities where name like '#{params[:search]}%'", page: params[:page])
    end
    cache_location if logged_in?
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
  def cities_names
    lol=[]
    City.all.each do |c|
      lol.append [c.name, c.id]
    end
    lol
  end
end

app/views/cities/_city.html.erb
<li>
  <% if !current_user.nil? && current_user.admin? %>
      <%= link_to "Zmazať", city, method: :delete, data: {confirm: "Naozaj?"}, class: 'btn btn-primary' %>
  <% end %>
  <%= link_to city do %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= city.name %></h3>
        </div>
        <div class="panel-body">
          <h4>Počet zon v meste: <%= city.areas.count %></h4>
          <h4>Počet registrovaných uživatelov z mesta: <%= city.users.count %></h4>
        </div>
      </div>
  <% end %>
</li>

app/views/cities/index.html.erb
<% provide(:title, 'Zoznam miest') %>
<h1>Zoznam miest</h1>

<%= form_tag(cities_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], class: "search-query", placeholder: "Bratislava", type: "search", data: {autocomplete: cities_autocomplete_city_name_path} %>
    <%= submit_tag "Hladať", class: "btn btn-primary" %>
<%end%>

<%= will_paginate if @cities%>

<ul class="cities">
  <%= render @cities if @cities%>
</ul>

app/views/cities/show.html.erb
<% provide(:title, @city.name) %>
<h1><%= @city.name %></h1>
<p>Počet návštevníkov stránky mesta: <%= @card %></p>
<div class="row">
  <div id="map-city" class="map col-md-10"></div>
</div>

<%= link_to "Pridať zónu", add_zone_path(id: "#{@city.id}"), class: "btn btn-lg btn-primary" %>

<%= content_tag :div, class: "city_class", data: {city: @city} do %>
<% end %>
<%= content_tag :div, class: "colors_class", data: {colors: @colors} do %>
<% end %>
<%= content_tag :div, class: "areas_class", data: {areas: @areas} do %>
<% end %>

<%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyABIzzN7SlW5GoZk7xOoBziqObZRw9TzsU&libraries=geometry&callback=initCityMap", defer: 'defer', async: 'async' %>